#include "A.h"




void A::perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--125-1--417950a2:16def139723:-8000:0000000000000885 begin
{
}
// section -64--88--125-1--417950a2:16def139723:-8000:0000000000000885 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::aire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--125-1--417950a2:16def139723:-8000:0000000000000893 begin
{
}
// section -64--88--125-1--417950a2:16def139723:-8000:0000000000000893 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
